Minor programming guide improvements
apache/beam pull request #12953
Opened 2020-09-27 16:56 UTC by milancermak

While going through the programming guide, I found two small things that can be improved.

First is in the [Windowing with bounded PCollections](https://beam.apache.org/documentation/programming-guide/#windowing-bounded-collections) section. The description mentions reading using `TextIO` but the images display reading from a database table via Kafka IO.

I've updated both diagrams (there's also a slight change in the text) to better reflect the content in the section.

Here's the "unwindowed" before & after:
<img width="1170" alt="unwindowed-before" src="https://user-images.githubusercontent.com/184055/94370803-9f964880-00e1-11eb-893c-1517f07cfe5e.png">
<img width="1176" alt="unwindowed-after" src="https://user-images.githubusercontent.com/184055/94370806-a329cf80-00e1-11eb-8b5f-0f3c2ba9d193.png">

Here's the "windowing" before & after:
<img width="1185" alt="windowing-before" src="https://user-images.githubusercontent.com/184055/94370822-be94da80-00e1-11eb-8e93-95f44ca93afb.png">
<img width="1193" alt="windowing-after" src="https://user-images.githubusercontent.com/184055/94370828-c05e9e00-00e1-11eb-99b8-ffbe1febf70b.png">

The second change is a minor one in the [Setting a trigger](https://beam.apache.org/documentation/programming-guide/#setting-a-trigger) section. The python example uses a code snippet from a test suite, but it is wrong with regards to the text - the text (and the Java snippet) use a one minute `afterProcessing` trigger whereas the incorrect snippet uses a 10 minute trigget (`10 * 60`). I've copy-pasted the whole code snippet and removed the now obsolete commands from the test suite.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apac [...]

2020-09-27 16:56 UTC, milancermak commented
R: @melap

2020-10-02 01:10 UTC, aaltay commented
R: @rosetn

2020-10-02 22:35 UTC, rosetn requested changes
Staged: http://apache-beam-website-pull-requests.storage.googleapis.com/12953/documentation/programming-guide/index.html#windowing-basics

Thanks for these updates! WDYT about updating Figure 3 so that these diagrams in series are consistent? The accompanying text does use KakfaIO, though, so you would have to change that as well.

2020-10-02 22:35 UTC, rosetn commented on website/www/site/content/en/documentation/programming-guide.md
> +As before, the pipeline creates a bounded `PCollection` of file lines. We
I'd replace "of file lines" with "by reading lines from a file using `TextIO`." I think how you have it earlier is clear.

2020-10-03 13:59 UTC, milancermak commented
Hi, thank you for the review.

Since Figure 3 pertains to an unbounded collection, to me it makes sense to me to have a KafkaIO transform there. I've changed the diagram so that it reads from a Kafka topic instead of a database table. That we the text doesn't have to updated either. Here's the before & after. 

<img width="1104" alt="windowing-pipeline-unbounded-before" src="https://user-images.githubusercontent.com/184055/94993430-73b31100-0580-11eb-92ef-2ab0c4d37058.png">
<img width="1117" alt="windowing-pipeline-unbounded-after" src="https://user-images.githubusercontent.com/184055/94993431-757cd480-0580-11eb-80c9-1347a7dc355d.png">


What do you think?

2020-10-07 23:29 UTC, rosetn commented
Thanks, Milan! Looks good. Can you add the `alt` attribute to the SVG files and provide some brief alternative text?

2020-10-08 11:55 UTC, milancermak commented
Can you please provide some guidance on how & where?

I found [this StackOverflow](https://stackoverflow.com/questions/4697100/accessibility-recommended-alt-text-convention-for-svg-and-mathml) post, but the SVGs already have a `title` tag that seems to be transformed into an `alt` attribute on the `img` tag in the rendered HTML. Should I update that?

2020-10-08 17:20 UTC, rosetn commented
Looking closer at the file, I see that there already is alt text that I've missed. Sorry about that! On this site and flavor of markdown, you can specify the alt text directly in the .md file, in the following format: ![Alternative text](/images/image-name.svg)

2020-10-08 17:20 UTC, rosetn approved these changes
Thanks again for the changes!

2020-10-08 17:47 UTC, aaltay commented
Run Python PreCommit

2020-10-08 19:10 UTC, merged