Remove unused endOfStreamMonitor from nexmark
apache/beam pull request #13435
Opened 2020-11-29 11:52 UTC by rHermes

The `endOfStreamMonitor` in the `NexmarkQuery` class is not used. This PR removes it.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [X] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [X] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [X] Update `CHANGES.md` with noteworthy changes.
 - [X] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

Post-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

Lang | SDK | Dataflow | Flink | Samza | Spark | Twister2
--- | --- | --- | --- | --- | --- | ---
Go | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/) | ---
Java | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/)
Python | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python36/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python37/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python38/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PreCommit_Python_PVR_Flink_Cron/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_Python_VR_Spark/lastCompletedBuild/) | ---
XLang | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Direct/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Dataflow/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Flink/lastCompletedBuild/) | --- | [![Build Status](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PostCommit_XVR_Spark/lastCompletedBuild/) | ---

Pre-Commit Tests Status (on master branch)
------------------------------------------------------------------------------------------------

--- |Java | Python | Go | Website | Whitespace | Typescript
--- | --- | --- | --- | --- | --- | ---
Non-portable | [![Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PreCommit_Java_Cron/lastCompletedBuild/) | [![Build Status](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PreCommit_Python_Cron/lastCompletedBuild/)<br>[![Build Status](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastCompletedBuild/badge/icon)](https://ci-beam.apache.org/job/beam_PreCommit_PythonLint_Cron/lastC [...]

2020-11-29 11:53 UTC, rHermes commented
R: @echauchot 
R: @aromanenko-dev

2020-11-29 11:55 UTC, rHermes commented
The spotless check failed with a file I have not edited :confused: I can apply the spotless fix and upload that here if you want?

2020-11-29 15:35 UTC, rHermes commented
Run Java PreCommit

2020-11-29 18:30 UTC, rHermes commented
Seems I've been a bit quick in the trigger here and changed the logic after merging the two distributions. I'll push a fix later this evening, sorry for the slip!

2020-11-30 08:52 UTC, rHermes commented
I've fixed the error, but the error now is not in a part of the code that I haven't touched.

2020-11-30 09:55 UTC, aromanenko-dev commented
Run Java PreCommit

2020-11-30 11:03 UTC, aromanenko-dev commented
@rHermes Thanks! Could you create a Jira for this and squash all your commits into one?

2020-11-30 12:05 UTC, rHermes commented
> @rHermes Thanks! Could you create a Jira for this and squash all your commits into one?

Will do it after work today :)

2020-11-30 13:42 UTC, rHermes commented
OK, squashed and created a JIRA issue.

2020-12-02 13:42 UTC, rHermes commented
@aromanenko-dev does it look good now?

2020-12-02 17:11 UTC, aromanenko-dev commented
@rHermes Thanks! Could you elaborate changes regarding this part `This PR ... merges the start and end distributions.` ?

2020-12-02 17:13 UTC, aromanenko-dev commented
@echauchot Could you take a look on this PR since you worked on Nexmark too?

2020-12-02 21:42 UTC, rHermes commented
> @rHermes Thanks! Could you elaborate the changes regarding this part `This PR ... merges the start and end distributions.` ? Why it was done?

Because they are updated with exactly the same values, they will always be exactly the same, so they could be merged. If you look at the removed lines in Monitor you will see that they where set with exactly the same values

2020-12-03 10:36 UTC, echauchot commented
@rHermes thanks for your work ! taking a look

2020-12-07 13:07 UTC, rHermes commented
> @rHermes thanks for your work ! taking a look

Any update on this?

2020-12-09 11:18 UTC, echauchot commented
@rHermes sorry I'm late on that I started the review and then I was dragged on other priorities. I think I could finish by the end of the week.

2020-12-14 11:15 UTC, echauchot commented
Run Direct Runner Nexmark Tests

2020-12-14 11:34 UTC, echauchot requested changes
Thanks for your work @rHermes !
Only some minor fixes and an important comment.
Nexmark execution times are similar to CI. So LGTM
On piece of advice, it is your second cleaning PR on nexmark. Next time, could you please consider submitting cleaning PRs all in a single PR with separate commits with explicit messages? thanks

2020-12-14 11:34 UTC, echauchot commented on sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/Monitor.java
> +    final Distribution systemTimestamp = Metrics.distribution(name, prefix + ".systemTimestamp");
it is not a timeStamp, it is in processing time (the wall clock) as opposed to a timestamp which is a component of an element put by the source. Please rename to "processingTime"

2020-12-14 11:34 UTC, echauchot commented on sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/NexmarkLauncher.java
> +    if (eventStart >= 0 && effectiveEnd >= eventStart) {
true that this expression is equivalent and simpler but less readable. I would prefer a revert

2020-12-14 11:34 UTC, echauchot commented on sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/NexmarkLauncher.java
> +    if (eventStart >= 0 && resultStart >= eventStart) {
same here

2020-12-14 11:34 UTC, echauchot commented on sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/Monitor.java
> +      systemTimestamp.update(System.currentTimeMillis());
agree with your simplification for these reasons:
- for each element processed, the distribution metrics start and end will be updated with the same value and, as the distribution reports min, max and average, and, as in _MetricsReader_ we are requesting the minimum and the maximum, there is no impact of having a single distribution
- the methods in _MetricsReader_ use a SplitIterator on the distributions that is not immutable for the underlying source (which could explain that there was 2 distributions created) but it does only reading (by calling _getMin()_ and _getMax()_) so there will be no side effect on the underlying distribution.

2020-12-16 18:43 UTC, rHermes commented
> Thanks for your work @rHermes !
> Only some minor fixes and an important comment.
> Nexmark execution times are similar to CI. So LGTM
> On piece of advice, it is your second cleaning PR on nexmark. Next time, could you please consider submitting cleaning PRs all in a single PR with separate commits with explicit messages? thanks

I thought it was better practice to create separate PRs, but it's easier for me to just combine them, so I'll do that next time :)

2020-12-17 08:29 UTC, echauchot commented
@rHermes yes general good practice is to separate PRs that deal with different subjects. But for cleaning PRs, it is the same subject. There a lot of leftovers in nexmark what I would like to avoid is tens of PRs that remove only a couple of fields.

2020-12-17 08:39 UTC, rHermes commented
> @rHermes yes general good practice is to separate PRs that deal with different subjects. But for cleaning PRs, it is the same subject. There a lot of leftovers in nexmark what I would like to avoid is tens of PRs that remove only a couple of fields.

Got it :+1: 

I've addressed your comments from the review, and rebased on top of master.

2021-01-07 08:16 UTC, echauchot commented on sdks/java/testing/nexmark/src/main/java/org/apache/beam/sdk/nexmark/Monitor.java
> +    final Distribution systemTimestamp = Metrics.distribution(name, prefix + ".systemTimestamp");
please rename also the metric name

2021-01-07 08:20 UTC, echauchot requested changes
@rHermes sorry for the delay. I took a llok at your changes. you just forgot a rename and I can merge.

2021-01-07 14:13 UTC, rHermes commented
> @rHermes sorry for the delay. I took a llok at your changes. you just forgot a rename and I can merge.

Ahh, my bad. Fixed now :)

2021-01-08 08:45 UTC, echauchot commented
Run Direct Runner Nexmark Tests

2021-01-08 08:45 UTC, echauchot commented
Run Direct Runner Nexmark Tests

2021-01-08 09:39 UTC, echauchot approved these changes
@rHermes thanks for your work! LGTM. Nexmark last results are correct, merging

2021-01-08 09:39 UTC, merged

2021-01-08 09:41 UTC, echauchot commented
my bad, I merged but I forgot to tell you to rename the commit with ticket number and to squash them. It is not that serious, just not very clear in history. you'll know for next time.