[BEAM-12313] - Initial changes to support Java 17 SDK Harness docker image
apache/beam pull request #15675
Opened 2021-10-07 00:26 UTC by fernando-wizeline

First "draft" to review the changes required to publish the Java 17 SDK Harness docker image.

@emilymye, if I'm not mistaken, you were in charge of the same effort but for the Java 11 SDK. Can you help me to review this and let me know what I'm missing?
Thanks a lot for the help!
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon">
        </a>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/badge/icon?subject=V1">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/badge/icon?subject=V1+Streaming">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/badge/icon?subject=V1+Java+11">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/badge/icon?subject=V2">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/badge/icon?subject=V2+Streaming">
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/badge/icon?subject=Java+8">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/badge/icon?subject=Java+11">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/badge/icon?subject=Portable">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/badge/icon?subject=Portable+Streaming">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/badge/icon">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/badge/icon?subject=Portable">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/badge/icon">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/badge/icon?subject=Portable">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/badge/icon?subject=Structured+Streaming">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/badge/icon">
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/badge/icon?subject=V1">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/badge/icon?subject=V2">
        < [...]

2021-10-12 20:27 UTC, kileys commented
Run Java_Examples_Dataflow PreCommit

2021-10-12 20:27 UTC, kileys commented
Run Python PreCommit

2021-10-29 19:44 UTC, kileys commented
@kennknowles can you take a look?

2021-11-03 16:40 UTC, kennknowles requested changes
Seems OK. We probably need the container to be checked in first before the Jenkins jobs can succeed.

2021-11-03 16:40 UTC, kennknowles commented on sdks/java/testing/test-utils/src/test/java/org/apache/beam/sdk/testutils/jvmverification/JvmVerification.java
> +    assertEquals(v17, getByteCodeVersion(JvmVerification.class));
Need to add an entry to `versionMapping`, right?

2021-11-03 17:11 UTC, fernando-wizeline commented
> Seems OK. We probably need the container to be checked in first before the Jenkins jobs can succeed.

Thanks @kennknowles! Does Infra takes care of checking in the container? I need to open a ticket in JIRA for that, right?

2021-11-03 17:53 UTC, kennknowles commented
> > Seems OK. We probably need the container to be checked in first before the Jenkins jobs can succeed.
> 
> Thanks @kennknowles! Does Infra takes care of checking in the container? I need to open a ticket in JIRA for that, right?

Our nightly snapshot pushes containers. I'm not super familiar with it - not sure if your change will already cause that to happen or not.

2021-11-09 19:21 UTC, pabloem commented
https://ci-beam.apache.org/job/beam_SeedJob/8826/console

2021-11-09 19:50 UTC, pabloem commented
seed job looks good : )

2021-11-09 20:15 UTC, fernando-wizeline commented
Run Java PreCommit

2021-11-12 16:59 UTC, fernando-wizeline commented
@pabloem what do you think? Would it be ok to merge this?

2021-11-16 18:22 UTC, fernando-wizeline commented
Run Java_Examples_Dataflow PreCommit

2021-11-16 20:58 UTC, pabloem commented
this looks fine to me, though I'll let @kennknowles finish the review as he had started doing it, and must have more context. Happy to help with seed jobs / etc

2021-11-23 16:35 UTC, fernando-wizeline commented
> this looks fine to me, though I'll let @kennknowles finish the review as he had started doing it, and must have more context. Happy to help with seed jobs / etc

Thanks @pabloem!
Hi @kennknowles! It seems we need to open a ticket similar to this one https://issues.apache.org/jira/browse/INFRA-20866 to create a sdk17 image. I tried opening a new one but I don't have the right JIRA permissions. That and the changes already contained in this PR should take care of everything related to the SDK 17 Harness.

2021-11-23 21:27 UTC, kileys commented
I had permissions to create a ticket: https://issues.apache.org/jira/browse/INFRA-22561

2021-11-29 16:09 UTC, fernando-wizeline commented
> I had permissions to create a ticket: https://issues.apache.org/jira/browse/INFRA-22561

Hi @kileys!
The repo was created but now we need someone to push an image. Do you know who can help us with that? It looks like last time Emily helped with that but I'm not sure if she can help this time.
Thanks!

2021-11-29 17:30 UTC, kileys commented
Do we just need to run the Jenkins job to publish an image?

2021-11-29 18:10 UTC, kileys commented
@fernando-wizeline were all the tests run successfully after the seed job? I don't see any runs on Jenkins

2021-11-29 18:50 UTC, fernando-wizeline commented
> @fernando-wizeline were all the tests run successfully after the seed job? I don't see any runs on Jenkins

hi @kileys! Yeah they did run successfully twenty days ago, but since then I added new ones.
@pabloem, can you help us by  kicking off the seed job again?

2021-11-29 19:00 UTC, kileys commented
After the seed job, you'll have to use the trigger phrase to actually have the tests run. The seed job doesn't start the new tests e.g. https://ci-beam.apache.org/job/beam_LoadTests_Java_ParDo_Dataflow_V2_Streaming_Java17_PR/

2021-11-29 19:09 UTC, tvalentyn commented
Seed job: https://ci-beam.apache.org/job/beam_SeedJob/8919/

2021-12-01 19:23 UTC, kennknowles commented
Are you unblocked here?

2021-12-01 20:18 UTC, fernando-wizeline commented
> Are you unblocked here?

Hi @kennknowles!
I am, but some of the new Java 17 tests failed during the execution of the seedjob.
It looks like a matter of setting up the Java Home correctly.
I'll be triaging that this week.

2021-12-14 21:14 UTC, fernando-wizeline commented
Run Load Tests Java 11 CoGBK Dataflow V2 Streaming

2021-12-15 05:19 UTC, tvalentyn commented on buildSrc/build.gradle.kts
> +  runtimeOnly("gradle.plugin.com.palantir.gradle.docker:gradle-docker:0.22.0")                             // Enable building Docker containers
do we need this one? i remember we switched to a different plugin earlier (the one that is used in other places in Beam).

2021-12-16 21:09 UTC, fernando-wizeline commented
hi @tvalentyn !
Can you help me to run the seed job for this again?
Thanks!

2021-12-17 02:54 UTC, tvalentyn commented
did that (it failed).

2021-12-17 16:36 UTC, fernando-wizeline commented
> did that (it failed).

Thanks @tvalentyn!
Can you share the link to the results page, please?

2021-12-17 16:36 UTC, fernando-wizeline commented
> > did that (it failed).
> 
> Thanks @tvalentyn! Can you share the link to the results page, please?

Found it, sorry!!!

2021-12-21 19:58 UTC, tvalentyn commented
no worries, feel free to ping this when you need another run.

2021-12-27 23:41 UTC, fernando-wizeline commented
hi @tvalentyn, 
Is there any chance of running the seed-job again?
Thanks!

2021-12-28 21:03 UTC, ibzib commented
https://ci-beam.apache.org/job/beam_SeedJob/9042

2021-12-28 23:08 UTC, fernando-wizeline commented
Run Load Tests Java 17 CoGBK Dataflow V2 Streaming

2021-12-29 16:35 UTC, fernando-wizeline commented
Run Load Tests Java 11 CoGBK Dataflow V2 Streaming

2021-12-29 21:23 UTC, fernando-wizeline commented
Run Direct ValidatesRunner Java 17

2021-12-29 21:34 UTC, fernando-wizeline commented
Run Direct ValidatesRunner Java 11

2021-12-29 22:38 UTC, ibzib commented
Looks like the seed job is permared: https://issues.apache.org/jira/browse/BEAM-13581

2022-01-04 18:32 UTC, fernando-wizeline commented
Hi @lukecwik!
It looks like the CoGBK load tests rely on the Caches class which in turn rely on the jamm library.
The jamm library is using a the setAccessible method which, per JEP403, no longer works and throws an InaccessibleObjectException instead.
What would you say is the best approach in this case?
Thanks a lot for the help! Sorry if I’m not seeing a pretty obvious solution here.

2022-01-07 22:53 UTC, lukecwik commented
--add-opens should be done for all modules that exist on the classpath and only access to jamm should be provided. If jamm doesn't support java 9 modules yet then we can modify the jar and embed a module-info in it so that we don't open all modules and packages to everyone.

2022-01-21 00:45 UTC, aaltay commented
What is the next step on this PR?

2022-01-21 02:26 UTC, kileys commented
This can be closed. There's a new PR with the jamm workaround

2022-01-21 04:38 UTC, closed without merging