[BEAM-13359] [Playground] Tag existing examples
apache/beam pull request #16147
Opened 2021-12-07 10:16 UTC by pavel-avilov

[[BEAM-13359]](https://issues.apache.org/jira/browse/BEAM-13359)
Tag existing examples

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon">
        </a>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/badge/icon?subject=V1">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/badge/icon?subject=V1+Streaming">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/badge/icon?subject=V1+Java+11">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/badge/icon?subject=V2">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/badge/icon?subject=V2+Streaming">
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/badge/icon?subject=Java+8">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/badge/icon?subject=Java+11">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/badge/icon?subject=Portable">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/badge/icon?subject=Portable+Streaming">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/badge/icon">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/badge/icon?subject=Portable">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/badge/icon">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/badge/icon?subject=Portable">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/badge/icon?subject=Structured+Streaming">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/badge/icon">
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/badge/icon?subject=V1">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/badge/icon?subject=V2">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Py_Va [...]

2021-12-08 11:45 UTC, ilya-kozyrev commented
Please add multifile flag in tag

2021-12-14 10:58 UTC, daria-malkova requested changes

2021-12-14 10:58 UTC, daria-malkova commented on sdks/go/examples/grades/grades.go
> +//   description: An example that combines grades data
Dot missing

2021-12-14 14:56 UTC, pavel-avilov commented on sdks/go/examples/grades/grades.go
> +//   description: An example that combines grades data
Done.

2021-12-17 09:35 UTC, KhaninArtur requested changes

2021-12-17 09:35 UTC, KhaninArtur commented on examples/java/src/main/java/org/apache/beam/examples/MinimalWordCount.java
> +//   description: An example that counts words in Shakespeare/kinglear.txt.
```suggestion
//   description: An example that counts words in Shakespeare's works.
```

2021-12-17 09:35 UTC, KhaninArtur commented on sdks/go/examples/minimal_wordcount/minimal_wordcount.go
> +//   description: An example that counts words in Shakespeare.
```suggestion
//   description: An example that counts words in Shakespeare's works.
```

2021-12-20 15:59 UTC, pavel-avilov commented on examples/java/src/main/java/org/apache/beam/examples/MinimalWordCount.java
> +//   description: An example that counts words in Shakespeare/kinglear.txt.
Done.

2021-12-20 15:59 UTC, pavel-avilov commented on sdks/go/examples/minimal_wordcount/minimal_wordcount.go
> +//   description: An example that counts words in Shakespeare.
Done.

2021-12-20 16:04 UTC, KhaninArtur approved these changes
LGTM

2021-12-22 14:57 UTC, daria-malkova approved these changes
LGTM

2021-12-22 15:24 UTC, pavel-avilov commented
R: @pabloem

2021-12-27 14:16 UTC, KhaninArtur approved these changes
LGTM

2021-12-28 09:40 UTC, ilya-kozyrev requested changes

2021-12-28 09:40 UTC, ilya-kozyrev commented on examples/java/src/main/java/org/apache/beam/examples/MinimalWordCount.java
> +//     - Options
```suggestion
//     - Combiners
//     - Filtering
//     - IO
//     - Core Transforms
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on examples/java/src/main/java/org/apache/beam/examples/WordCount.java
> +//     - Options
```suggestion
//     - Combiners
//     - Options
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on examples/java/src/main/java/org/apache/beam/examples/cookbook/DistinctExample.java
> +//     - IO
```suggestion
//     - Filtering
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/contains/contains.go
> +//     - Options
```suggestion
//     - Filtering
//     - Options
//     - Debugging
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/debugging_wordcount/debugging_wordcount.go
> +//	   - Options
```suggestion
//     - Options
//     - Filtering
//     - Debugging
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/forest/forest.go
> +//     - Testing
```suggestion
//     - Flatten
//     - Branching
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/grades/grades.go
> +//     - Combiners
```suggestion
//     - Debugging
//     - Combiners
//     - Filtering
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/minimal_wordcount/minimal_wordcount.go
> +//     - IO
```suggestion
//     - IO
//     - Combiners
//     - Core Transforms
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/multiout/multiout.go
> +//     - Options
```suggestion
//     - Options
//     - Branching
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/windowed_wordcount/windowed_wordcount.go
> +//     - IO
```suggestion
//     - Windowing
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/wordcount/wordcount.go
> +//     - IO
```suggestion
//     - Combiners
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/python/apache_beam/examples/wordcount.py
> +#     - IO
```suggestion
#     - Combiners
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/python/apache_beam/examples/wordcount_debugging.py
> +#     - Options
```suggestion
#     - Options
#     - Combiners
#     - Filtering
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/python/apache_beam/examples/wordcount_debugging.py
> +#     - IO
```suggestion
#     - Flatten
#     - Debugging
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/python/apache_beam/examples/wordcount_minimal.py
> +#     - IO
```suggestion
#     - IO
#     - Core Transforms
#     - Flatten
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/python/apache_beam/examples/wordcount_with_metrics.py
> +#     - IO
```suggestion
#     - Combiners
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on examples/java/src/main/java/org/apache/beam/examples/DebuggingWordCount.java
> +//     - Options
@pavel-avilov could we add debugging to categories? To categorize examples with debug logs

2021-12-28 09:40 UTC, ilya-kozyrev commented on playground/categories.yaml
> +  - Beam SQL
```suggestion
  - Beam SQL
  - Debugging
```

2021-12-28 09:40 UTC, ilya-kozyrev commented on sdks/go/examples/stringsplit/stringsplit.go
> +//     - Testing
```suggestion
//     - Debugging
//     - Flatten
```

2021-12-28 10:07 UTC, KhaninArtur requested changes

2021-12-28 10:07 UTC, KhaninArtur commented on sdks/python/apache_beam/examples/wordcount_minimal.py
> +#     - IO
I think, we should also add `Combiners`

2021-12-28 11:48 UTC, KhaninArtur commented on playground/categories.yaml
> +  - Beam SQL
```suggestion
  - Beam SQL
  - Debugging
  - Filtering
  - Flatten
  - Core Transforms
```

2021-12-28 12:54 UTC, pavel-avilov commented on examples/java/src/main/java/org/apache/beam/examples/DebuggingWordCount.java
> +//     - Options
Done.

2021-12-28 12:56 UTC, pavel-avilov commented on examples/java/src/main/java/org/apache/beam/examples/cookbook/DistinctExample.java
> +//     - IO
Done.

2021-12-28 13:03 UTC, pavel-avilov commented on sdks/python/apache_beam/examples/wordcount_minimal.py
> +#     - IO
Done.

2021-12-28 13:08 UTC, pavel-avilov commented
@ilya-kozyrev @KhaninArtur  I added all your suggested changes

2021-12-29 15:12 UTC, KhaninArtur approved these changes
LGTM

2022-01-06 01:37 UTC, pabloem commented
LGTM

2022-01-10 23:44 UTC, merged