[BEAM-13395] [Playground] Tag katas
apache/beam pull request #16192
Opened 2021-12-10 08:05 UTC by pavel-avilov

[[BEAM-13395]](https://issues.apache.org/jira/browse/BEAM-13395)
Tag java and python katas

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

`ValidatesRunner` compliance status (on master branch)
--------------------------------------------------------

<table>
  <thead>
    <tr>
      <th>Lang</th>
      <th>ULR</th>
      <th>Dataflow</th>
      <th>Flink</th>
      <th>Samza</th>
      <th>Spark</th>
      <th>Twister2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Go</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go/lastCompletedBuild/badge/icon">
        </a>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Flink/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Samza/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Go_VR_Spark/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>---</td>
    </tr>
    <tr>
      <td>Java</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_ULR/lastCompletedBuild/badge/icon">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow/lastCompletedBuild/badge/icon?subject=V1">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Streaming/lastCompletedBuild/badge/icon?subject=V1+Streaming">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_Java11/lastCompletedBuild/badge/icon?subject=V1+Java+11">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2/lastCompletedBuild/badge/icon?subject=V2">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_VR_Dataflow_V2_Streaming/lastCompletedBuild/badge/icon?subject=V2+Streaming">
        </a><br>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink/lastCompletedBuild/badge/icon?subject=Java+8">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_Java11/lastCompletedBuild/badge/icon?subject=Java+11">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Batch/lastCompletedBuild/badge/icon?subject=Portable">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Flink_Streaming/lastCompletedBuild/badge/icon?subject=Portable+Streaming">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Samza/lastCompletedBuild/badge/icon">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Samza/lastCompletedBuild/badge/icon?subject=Portable">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark/lastCompletedBuild/badge/icon">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_PVR_Spark_Batch/lastCompletedBuild/badge/icon?subject=Portable">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming/lastCompletedBuild/badge/icon?subject=Structured+Streaming">
        </a>
      </td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Twister2/lastCompletedBuild/badge/icon">
        </a>
      </td>
    </tr>
    <tr>
      <td>Python</td>
      <td>---</td>
      <td>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow/lastCompletedBuild/badge/icon?subject=V1">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_Py_VR_Dataflow_V2/lastCompletedBuild/badge/icon?subject=V2">
        </a><br>
        <a href="https://ci-beam.apache.org/job/beam_PostCommit_Py_ValCont/lastCompletedBuild/">
          <img alt="Build Status" src="https://ci-beam.apache.org/job/beam_PostCommit_P [...]

2021-12-10 08:06 UTC, pavel-avilov commented
R: @KhaninArtur @ilya-kozyrev @daria-malkova @AydarZaynutdinov

2021-12-10 09:32 UTC, daria-malkova requested changes

2021-12-10 09:32 UTC, daria-malkova commented on learning/katas/java/Core Transforms/Combine/BinaryCombineFn Lambda/src/org/apache/beam/learning/katas/coretransforms/combine/binarycombinefnlambda/Task.java
> +//   description: Task from katas to implements the summation of BigInteger using lambda or method reference.
just lambda

2021-12-10 11:33 UTC, KhaninArtur requested changes

2021-12-10 11:33 UTC, KhaninArtur commented on learning/katas/java/Core Transforms/Side Output/Side Output/src/org/apache/beam/learning/katas/coretransforms/sideoutput/Task.java
> +//     - Testing
```suggestion
//     - Testing
//     - Multiple Outputs
```

2021-12-10 11:33 UTC, KhaninArtur commented on learning/katas/java/Windowing/Fixed Time Window/Fixed Time Window/src/org/apache/beam/learning/katas/windowing/fixedwindow/Task.java
> +//     - Testing
```suggestion
//     - Combiners
//     - Testing
```

2021-12-10 11:33 UTC, KhaninArtur commented on learning/katas/python/Core Transforms/Side Output/Side Output/task.py
> +#     - Testing
```suggestion
#     - Testing
#     - Multiple Outputs
```

2021-12-10 12:53 UTC, pavel-avilov commented on learning/katas/python/Core Transforms/Side Output/Side Output/task.py
> +#     - Testing
Done

2021-12-10 12:53 UTC, pavel-avilov commented on learning/katas/java/Windowing/Fixed Time Window/Fixed Time Window/src/org/apache/beam/learning/katas/windowing/fixedwindow/Task.java
> +//     - Testing
Done

2021-12-10 12:53 UTC, pavel-avilov commented on learning/katas/java/Core Transforms/Side Output/Side Output/src/org/apache/beam/learning/katas/coretransforms/sideoutput/Task.java
> +//     - Testing
Done

2021-12-10 12:53 UTC, pavel-avilov commented on learning/katas/java/Core Transforms/Combine/BinaryCombineFn Lambda/src/org/apache/beam/learning/katas/coretransforms/combine/binarycombinefnlambda/Task.java
> +//   description: Task from katas to implements the summation of BigInteger using lambda or method reference.
Done

2021-12-10 15:49 UTC, KhaninArtur requested changes

2021-12-10 15:49 UTC, KhaninArtur commented on learning/katas/java/Core Transforms/Map/FlatMapElements/src/org/apache/beam/learning/katas/coretransforms/map/flatmapelements/Task.java
> +//       into splitted whitespace (" ").
```suggestion
//       into words splitted by whitespace (" ").
```

2021-12-10 15:49 UTC, KhaninArtur commented on learning/katas/java/Core Transforms/Map/ParDo OneToMany/src/org/apache/beam/learning/katas/coretransforms/map/pardoonetomany/Task.java
> +//   description: Task from katas that maps each input sentence into splitted whitespace (" ").
```suggestion
//   description: Task from katas that maps each input sentence into words splitted by whitespace (" ").
```

2021-12-10 15:49 UTC, KhaninArtur commented on learning/katas/python/Core Transforms/Map/FlatMap/task.py
> +#       into splitted whitespace (" ").
```suggestion
#       into words splitted by whitespace (" ").
```

2021-12-10 15:49 UTC, KhaninArtur commented on learning/katas/python/Core Transforms/Map/ParDo OneToMany/task.py
> +#   description: Task from katas is a ParDo that maps each input sentence into splitted whitespace (" ").
```suggestion
#   description: Task from katas is a ParDo that maps each input sentence into words splitter by whitespace (" ").
```

2021-12-14 08:25 UTC, pavel-avilov commented on learning/katas/java/Core Transforms/Map/FlatMapElements/src/org/apache/beam/learning/katas/coretransforms/map/flatmapelements/Task.java
> +//       into splitted whitespace (" ").
Done.

2021-12-14 08:25 UTC, pavel-avilov commented on learning/katas/java/Core Transforms/Map/ParDo OneToMany/src/org/apache/beam/learning/katas/coretransforms/map/pardoonetomany/Task.java
> +//   description: Task from katas that maps each input sentence into splitted whitespace (" ").
Done.

2021-12-14 08:26 UTC, pavel-avilov commented on learning/katas/python/Core Transforms/Map/FlatMap/task.py
> +#       into splitted whitespace (" ").
Done.

2021-12-14 12:40 UTC, KhaninArtur approved these changes
LGTM

2021-12-14 17:09 UTC, ilya-kozyrev requested changes
Just want to add new categories and reduce combiners

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Common Transforms/Filter/ParDo/task.py
> +#     - Combiners
```suggestion
#     - Filtering
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Branching/Branching/task.py
> +#     - Combiners
```suggestion
#     - Branching
#     - Multiple Outputs
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Composite Transform/Composite Transform/task.py
> +#     - Combiners
```suggestion
#     - Flatten
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Flatten/Flatten/task.py
> +#     - Combiners
```suggestion
#     - Flatten
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Map/FlatMap/task.py
> +#     - Combiners
```suggestion
#     - Core Transforms
#     - Flatten
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Map/Map/task.py
> +#     - Combiners
```suggestion
#     - Core Transforms
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Map/ParDo OneToMany/task.py
> +#     - Combiners
```suggestion
#     - Core Transforms
#     - Flatten
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Map/ParDo/task.py
> +#     - Combiners
```suggestion
#     - Core Transforms
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Partition/Partition/task.py
> +#     - Combiners
```suggestion
#     - Multiple Outputs
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Side Input/Side Input/task.py
> +#     - Combiners
```suggestion

```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Core Transforms/Side Output/Side Output/task.py
> +#     - Combiners
```suggestion
#     - Filtering
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Windowing/Adding Timestamp/ParDo/task.py
> +#     - Combiners
```suggestion
#     - Streaming
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on learning/katas/python/Windowing/Fixed Time Window/Fixed Time Window/task.py
> +#     - Combiners
```suggestion
#     - Streaming
```

2021-12-14 17:09 UTC, ilya-kozyrev commented on playground/categories.yaml
> +  - Beam SQL
```suggestion
  - Beam SQL
  - Filtering
  - Branching
  - Flatten
  - Core Transforms
```

2021-12-15 13:47 UTC, pavel-avilov commented
@ilya-kozyrev I added all your suggested changes

2021-12-17 09:38 UTC, KhaninArtur approved these changes

2021-12-20 17:45 UTC, ilya-kozyrev approved these changes
LGTM

2021-12-21 13:35 UTC, daria-malkova approved these changes
LGTM

2021-12-21 15:56 UTC, pavel-avilov commented
R: @pabloem

2021-12-21 15:59 UTC, pabloem commented on playground/categories.yaml
> +  - Core Transforms
these lines seem to be repeated

2021-12-21 15:59 UTC, pabloem commented on learning/katas/python/Windowing/Fixed Time Window/Fixed Time Window/task.py
> +#     - Streaming
```suggestion
#     - Streaming
#     - Windowing
#     - Combiners
```

2021-12-22 09:22 UTC, pavel-avilov commented on learning/katas/python/Windowing/Fixed Time Window/Fixed Time Window/task.py
> +#     - Streaming
I agree, done.

2021-12-22 09:23 UTC, pavel-avilov commented on playground/categories.yaml
> +  - Core Transforms
Done.

2022-01-05 20:54 UTC, pabloem commented
LGTM

2022-01-05 20:54 UTC, merged

2022-02-06 19:11 UTC, iht commented
The answers to the katas for the Edu plugin of PyCharm/IntelliJ are now in wrong locations, and the katas are not working. Please update also the placeholders when modifying the text of the katas. I am working on a fix to this problem ([BEAM-13836](https://issues.apache.org/jira/browse/BEAM-13836).