[BEAM-13015] Clarify ownership of the list for state caching across bundles
apache/beam pull request #16982
Opened 2022-03-02 11:28 UTC by scwhittle

Minor cleanup noticed while looking at code

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2022-03-02 11:28 UTC, scwhittle commented
R: @lukecwik

2022-03-10 23:48 UTC, lukecwik approved these changes
Ignore this LGTM.

2022-03-10 23:54 UTC, lukecwik reviewed
Did we want to make a copy?

We could update the doc saying that this method takes ownership over the list.

Note that the two callers of this method `BagUserState` and `MultimapUserState` only have a lifespan of a single bundle so after the bundle completes they relinquish ownership over the list since `FnApiStateAccessor` clears the `stateKeyObjectCache` in finalizeState. We would definitely want to do this if we wanted to have `BagUserState` and `MultimapUserState` live beyond a single bundle.

2022-03-18 18:52 UTC, lukecwik requested changes
ignore earlier lgtm

2022-03-21 10:57 UTC, scwhittle commented
R: @lukecwik updated to take ownership and added some comments, PTAL

2022-03-21 21:23 UTC, lukecwik approved these changes

2022-03-21 21:23 UTC, lukecwik commented on sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/BagUserState.java
> +      // Note this takes ownership of newValues.
```suggestion
      // Note this takes ownership of newValues. This object is no longer used after it has been closed.
```

2022-03-22 21:10 UTC, lukecwik commented
Run Java PreCommit

2022-03-23 00:49 UTC, lukecwik commented
Run Java PreCommit

2022-03-23 03:54 UTC, lukecwik approved these changes

2022-03-23 03:54 UTC, lukecwik commented on sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/BagUserState.java
> +      // Note this takes ownership of newValues. This object is no longer used after it has been closed.
```suggestion
      // Note this takes ownership of newValues. This object is no longer used after it has been
      // closed.
```

2022-03-23 04:51 UTC, merged