[BREAM-13888] Add unit testing to ioutilx
apache/beam pull request #17058
Opened 2022-03-09 21:15 UTC by Abacn

Add unit testing for everything in ioutilx package

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment ( @jrmccluskey ).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2022-03-09 22:08 UTC, jrmccluskey requested changes
Good start! Have some style changes for you to make and a few things that leverage Go features.

2022-03-09 22:08 UTC, jrmccluskey commented on sdks/go/pkg/beam/core/util/ioutilx/read_test.go
> +	if (len(data) != testLength) {
No need to use the parentheses here, and you can use local variable assignment within the if statement to make your error message formatting more concise:
```suggestion
	if got, want := len(data),  testLength; got != want {
	     t.Errorf("got length %v, want %v", got, want)
	}
```

2022-03-09 22:08 UTC, jrmccluskey commented on sdks/go/pkg/beam/core/util/ioutilx/read_test.go
> +	if (string(data) != testString) {
Same pattern with the parentheses and "got, want" style here

2022-03-09 22:08 UTC, jrmccluskey commented on sdks/go/pkg/beam/core/util/ioutilx/read_test.go
> +func TestReadUnsafe(t *testing.T) {
Same style comments as above

2022-03-09 22:08 UTC, jrmccluskey commented on sdks/go/pkg/beam/core/util/ioutilx/read_test.go
> +func TestReadNBufUnsafe(t *testing.T) {
Same style comments as above

2022-03-09 22:08 UTC, jrmccluskey commented on sdks/go/pkg/beam/core/util/ioutilx/read_test.go
> +	length, err := ReadUnsafe(r, data[:])
You should be able to pass `data` here without specifying the range for the slice. 

```suggestion
	length, err := ReadUnsafe(r, data)
```

2022-03-09 22:08 UTC, jrmccluskey commented on sdks/go/pkg/beam/core/util/ioutilx/write_test.go
> +	var buff bytes.Buffer
Nit: Go style usually calls this `buf`

2022-03-09 22:08 UTC, jrmccluskey commented on sdks/go/pkg/beam/core/util/ioutilx/write_test.go
> +func TestWriteUnsafe(t *testing.T) {
Same style comments as in write.

2022-03-09 22:09 UTC, jrmccluskey commented
Also: fix the typo in the PR title so it gets mapped to the Jira ticket properly, and when you request a reviewer you do it in a follow-up comment and not the body of the PR template.

2022-03-10 16:49 UTC, Abacn commented
@jrmccluskey Thanks for feedbacks! Comments addressed.

2022-03-10 16:52 UTC, jrmccluskey commented on sdks/go/pkg/beam/core/util/ioutilx/read_test.go
> +	if got, want := string(data[:]), testString; got != want {
```suggestion
	if got, want := string(data), testString; got != want {
```

2022-03-10 16:56 UTC, jrmccluskey approved these changes
LGTM, going to add a committer so the workflows can run and we can get this merged in!

2022-03-10 16:57 UTC, Abacn commented
Sorry, missed a few style change request and fixed.

2022-03-10 16:58 UTC, jrmccluskey commented
R: @youngoli

2022-03-14 20:46 UTC, johnjcasey commented
LGTM

2022-03-16 04:03 UTC, youngoli requested changes
Looks really good. I'm being a bit more nitpicky than I usually would be just to explain Go conventions, but even then this is nearly there.

2022-03-16 15:06 UTC, Abacn commented
@youngoli Thanks for feedbacks! Comments addressed.

2022-03-16 18:06 UTC, youngoli approved these changes
Looks good to me!

2022-03-16 18:07 UTC, merged