[BEAM-14078] [Website] change link
apache/beam pull request #17077
Opened 2022-03-11 17:11 UTC by bullet03

[BEAM-14078]
- update link:
from (https://frontend-beta-dot-apache-beam-testing.appspot.com/)
to (https://play.beam.apache.org/)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2022-03-11 17:11 UTC, bullet03 commented
R: @AydarZaynutdinov

2022-03-11 17:17 UTC, AydarZaynutdinov approved these changes
LGTM

2022-03-14 18:04 UTC, AydarZaynutdinov requested changes

2022-03-14 18:04 UTC, AydarZaynutdinov commented on website/www/site/content/en/get-started/try-beam-playground.md
>  You can try an Apache Beam examples at
```suggestion
You can try the available Apache Beam examples at
```

2022-03-15 23:04 UTC, dariabezkorovaina commented
@pcoet please take a look:)

2022-03-15 23:49 UTC, pcoet requested changes

2022-03-15 23:49 UTC, pcoet commented on website/www/site/content/en/get-started/try-beam-playground.md
> +You can try the available Apache Beam examples a
This should be "examples at", right?

2022-03-16 07:40 UTC, AydarZaynutdinov commented on website/www/site/content/en/get-started/try-beam-playground.md
> +You can try the available Apache Beam examples a
Changed.

2022-03-16 18:43 UTC, pcoet approved these changes

2022-03-19 00:32 UTC, pabloem commented
LGTM thanks!

2022-03-19 00:33 UTC, merged