[BEAM-13229] [Website]
apache/beam pull request #17638
Opened 2022-05-12 15:17 UTC by bullet03

- add refresh method to scrollspy on language-switch.js and page-nav.js
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2022-05-12 15:17 UTC, bullet03 commented
R: @nausharipov

2022-05-19 15:43 UTC, aromanenko-dev requested changes
Please, squash the commits and rebase it against `master` instead of merging `master` into the feature branch.

2022-05-20 15:59 UTC, nausharipov commented on website/www/site/assets/js/language-switch-v2.js
> +          def = conf["default"],
please, format the file

2022-05-20 16:03 UTC, nausharipov commented on website/www/site/assets/js/language-switch-v2.js
> +                    // Set scroll to new position because Safari and Firefox can't do it automatically, only Chrome under the good detects the correct position of viewport
a typo: "Chrome under the good"

2022-05-20 16:13 UTC, nausharipov commented on website/www/site/assets/js/language-switch-v2.js
> +function getElPreviousPositionAndData(el) {
let's change "el" to "element"

2022-05-23 06:14 UTC, bullet03 commented on website/www/site/assets/js/language-switch-v2.js
> +                    // Set scroll to new position because Safari and Firefox can't do it automatically, only Chrome under the good detects the correct position of viewport
done

2022-05-23 06:14 UTC, bullet03 commented on website/www/site/assets/js/language-switch-v2.js
> +function getElPreviousPositionAndData(el) {
done

2022-05-23 06:15 UTC, bullet03 commented on website/www/site/assets/js/language-switch-v2.js
> +          def = conf["default"],
done

2022-05-23 07:25 UTC, bullet03 commented
We have cherry-picked and squashed commits from this branch into the new branch: https://github.com/apache/beam/pull/17731

2022-05-23 07:25 UTC, closed without merging