[Website] update check-links
apache/beam pull request #22221
Opened 2022-07-11 15:27 UTC by bullet03

- update check-links.sh script
- add func to find absolute links, leading to prod and staging
- add manually verified list with links that should be ignored
- sort invalid links by error code status
------------------------
before:
![before_ch](https://user-images.githubusercontent.com/61748758/194071865-2f5b7a0c-cdf4-46c3-9fc6-4c8a7f5cbd6a.JPG)
after:
- checking absolute production links
![after_ch_1](https://user-images.githubusercontent.com/61748758/194072146-ae1f8aed-8a5e-4831-b232-8f9f57e8da5d.JPG)
![after_ch_3](https://user-images.githubusercontent.com/61748758/194072169-e17df037-252d-4c20-af0f-9c93bc82b7b1.JPG)
- checking staging links
![after_ch_2](https://user-images.githubusercontent.com/61748758/194072225-e2e5971d-801e-4af0-8ee0-5f7607f9151f.JPG)
![after_ch_4](https://user-images.githubusercontent.com/61748758/194072240-6186577a-97ff-4a80-a07b-294767eeb73a.JPG)
- invalid links sorted by error status code
![after_ch_5](https://user-images.githubusercontent.com/61748758/194072339-f9234464-27ae-4230-af1f-906972797f0b.JPG)
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2022-12-22 16:57 UTC, bullet03 commented
R: @aromanenko-dev, could you kindly help with review?

2022-12-27 15:21 UTC, aromanenko-dev requested changes
Please, check the naming of methods and variable names.

Do we run this script automatically? What is an example of he output?

2022-12-28 09:30 UTC, bullet03 commented on website/www/check-links.sh
> +      curlResult=$(curl -sSfL --max-filesize 1000000 --max-time 10 --connect-timeout 10 --retry 2 -4 "$external_link" 2>&1 > /dev/null) && status=$? || status=$?
changed

2022-12-28 09:30 UTC, bullet03 commented on website/www/check-links.sh
> +function handleUrls {
> nit: use the same naming style format, rename to `handle_urls`

changed

2022-12-28 09:38 UTC, bullet03 commented
> Please, check the naming of methods and variable names.
> 
> Do we run this script automatically? What is an example of he output?

- Yes, script is run automatically
- Example of the output:
![5](https://user-images.githubusercontent.com/61748758/209791207-abda84bd-1177-4839-9a61-14264ca52668.jpg)
![6](https://user-images.githubusercontent.com/61748758/209791180-bd8bef11-4a85-4b26-835a-e4756b999a43.jpg)
![7](https://user-images.githubusercontent.com/61748758/209791183-ccaa236d-fd22-4c79-a68c-ad7ea1e357c2.jpg)

Example of the output is also provided in the description of the PR.

2022-12-28 14:15 UTC, aromanenko-dev approved these changes
LGTM

2022-12-28 14:16 UTC, merged