[Playground][Frontend] Tags filter for Examples Catalog (#22074)
apache/beam pull request #23532
Opened 2022-10-07 04:20 UTC by nausharipov

Resolves #22074 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2022-10-07 10:36 UTC, alexeyinkin requested changes

2022-10-07 10:36 UTC, alexeyinkin commented on playground/frontend/lib/pages/playground/states/example_selector_state.dart
> +  List<ExampleBase> filterExamplesByTags(List<ExampleBase> examples) {
`@visibleForTesting` here and below.

2022-10-07 10:36 UTC, alexeyinkin commented on playground/frontend/lib/pages/playground/states/example_selector_state.dart
> +    if (searchText.isEmpty) {
`_searchText` here and below.

2022-10-07 10:36 UTC, alexeyinkin commented on playground/frontend/playground_components/lib/src/cache/example_cache.dart
> +      // TODO(nausharipov): should tags be empty?
Yes. You may delete this comment.

2022-10-07 10:36 UTC, alexeyinkin commented on playground/frontend/playground_components/lib/src/controllers/example_loaders/content_example_loader.dart
> +    // TODO(nausharipov): should tags be empty?
Yes. You may delete this comment.

2022-10-07 10:36 UTC, alexeyinkin commented on playground/frontend/playground_components/pubspec.lock
> +# Generated by pub
Please delete this file. Libraries should not version-control `pubspec.lock`.
I will soon add it to `.gitignore`.

2022-10-07 10:36 UTC, alexeyinkin commented on playground/frontend/playground_components/test/src/common/categories.dart
> +import 'package:playground_components/playground_components.dart';
Please import specific files and not this bulk library.

2022-10-07 10:36 UTC, alexeyinkin commented on playground/frontend/playground_components/test/src/common/categories.dart
> +    examples: [exampleMock1, exampleMock2, exampleMock2, exampleMock2],
Are they repeated to test that 'tag2' is more frequent than 'tag1'? If so, explain in a comment please.

2022-10-07 10:36 UTC, alexeyinkin commented on playground/frontend/test/pages/playground/states/example_selector_state_test.dart
> +  // TODO(nausharipov): replace all 'sort' with 'filter' if ok
Do replace please.

2022-10-09 09:55 UTC, nausharipov commented on playground/frontend/lib/pages/playground/states/example_selector_state.dart
> +          if (tagsPopularity[tag] != null) {
Saved parentheses for readability.

2022-10-09 10:29 UTC, nausharipov commented on playground/frontend/lib/modules/examples/components/filter/filter.dart
> +        child: SingleChildScrollView(
<img width="723" alt="Screen Shot 2022-10-09 at 16 27 39" src="https://user-images.githubusercontent.com/31556582/194751705-6266f01d-6482-4453-b5fa-815452bfef80.png">

2022-10-10 02:55 UTC, alexeyinkin approved these changes
LGTM (internal review).

2022-10-10 06:28 UTC, nausharipov commented
R: @damondouglas

2022-10-14 02:51 UTC, damondouglas approved these changes
@pabloem LGTM
Thank you @nausharipov and @alexeyinkin :-)

2022-10-18 16:30 UTC, pabloem commented
lgtm!

2022-10-18 16:30 UTC, merged