JDBC SchemaTransform implementation. Need to break out into a separat…
apache/beam pull request #24918
Opened 2023-01-06 07:06 UTC by byronellis

SchemaTransform implementation for JdbcIO. Follows the pattern of various other SchemaTransforms, splitting Read and Write into separate transforms and using a URN pattern consistent with other transforms such as Kafka. Configurations are largely intended to match the existing SchemaIO implementation (which appears that it might have issues with usernames and passwords, but would handle that in a separate PR)

Fixes #21408

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2023-01-06 16:48 UTC, Abacn commented
R: @ahmedabu98 for schema transform PRs

2023-01-07 00:04 UTC, ahmedabu98 requested changes
Looks good! Just a few nits about how we check for "null" configuration fields here.

2023-01-07 04:09 UTC, byronellis commented on sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java
> +          JdbcIO.DataSourceConfiguration.create(config.getDriverClassName(), config.getJdbcUrl())
Updated validation to check for blank strings

2023-01-07 04:09 UTC, byronellis commented on sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java
> +          if (fetchSize != null) {
Yup, I also modified username and password to account for this behavior as well.

2023-01-07 04:10 UTC, byronellis commented on sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java
> +    if (configuration.getReadQuery() != null && configuration.getLocation() != null) {
Started getting a little overloaded so I moved stuff to a validate method and applied changes.

2023-01-09 19:01 UTC, ahmedabu98 requested changes
Thank you for the changes! Just a couple more nits

2023-01-10 15:57 UTC, byronellis commented on sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProviderTest.java
> +  public void testInvalidWriteSchemaOptions() {
Good catch! Moved.

2023-01-10 15:57 UTC, byronellis commented on sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java
> +      }
Sure thing. Done.

2023-01-10 16:07 UTC, ahmedabu98 approved these changes
LGTM, thanks for implementing this SchemaTransform!

@Abacn can you merge this when tests pass?

2023-01-10 18:59 UTC, Abacn commented
Looks like jenkins was down shortly and tests not ran

2023-01-10 18:59 UTC, Abacn commented
retest this please

2023-01-10 20:08 UTC, byronellis commented
Took the opportunity to add a couple of documentation blurbs :-)

2023-01-10 21:47 UTC, byronellis commented
@Abacn All tests are now passing

2023-01-10 21:56 UTC, merged

2023-01-10 21:57 UTC, Abacn commented
Thanks @byronellis @ahmedabu98 !