Bumping up the Cloud libraries bom and spanner java client libraries version
apache/beam pull request #26006
Opened 2023-03-28 04:22 UTC by darshan-sj

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

2023-03-28 07:03 UTC, darshan-sj commented
Run Java_GCP_IO_Direct PreCommit

2023-03-28 08:20 UTC, darshan-sj commented
Run Java_GCP_IO_Direct PreCommit

2023-03-28 13:51 UTC, Abacn commented
Thanks, BOM dep update also need to sync with a few dependencies defined in BeamModulePlugin. Usually we update BOM dep once per release, the last time was #25790

2023-03-30 17:38 UTC, darshan-sj commented
Linkage check tool log -- https://gist.github.com/darshan-sj/43f001e8d51dbc0297bc0b754abff8b5

2023-03-30 18:24 UTC, suztomo requested changes
Can you update GAX version? https://github.com/googleapis/java-cloud-bom/releases/tag/v26.11.0

> GAX: 2.23.3


Line 489


It's good that linkage checker tool is not reporting failures. Thank you for checking.

2023-03-30 18:35 UTC, darshan-sj commented
done

2023-03-30 19:24 UTC, suztomo requested changes

2023-03-30 19:24 UTC, suztomo commented on buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy
>          // https://github.com/googleapis/java-cloud-bom/releases/tag/v26.10.0
Can you replace any occurrence of "26.10.0" with "26.11.0"?

2023-03-31 08:01 UTC, darshan-sj commented
Run Java_Spark3_Versions PreCommit

2023-03-31 12:34 UTC, suztomo approved these changes

2023-03-31 13:55 UTC, darshan-sj commented
Run Java PreCommit

2023-03-31 13:57 UTC, darshan-sj commented
Run Java PreCommit

2023-03-31 18:39 UTC, darshan-sj commented
Run Java_GCP_IO_Direct PreCommit

2023-03-31 18:40 UTC, darshan-sj commented
Run Java_GCP_IO_Direct PreCommit

2023-03-31 18:41 UTC, darshan-sj commented
Run Java_PVR_Flink_Batch PreCommit

2023-03-31 18:41 UTC, darshan-sj commented
Run Java_Spark3_Versions PreCommit

2023-03-31 18:48 UTC, suztomo commented
Run Java_GCP_IO_Direct PreCommit

2023-03-31 18:48 UTC, suztomo commented
Run Java_Spark3_Versions PreCommit

2023-04-02 02:33 UTC, suztomo commented
4 skipped and 62 successful checks.

2023-04-02 02:37 UTC, merged