Update BigQueryIO Documentation
apache/beam pull request #28591
Opened 2023-09-21 15:47 UTC by RyuSA

- Updated the description regarding failed rows for Storage Write API.
- Made `PCollection` formatting consistent.

**Please** add a meaningful description for your change here

fixes #27298 

Current [documentation](https://beam.apache.org/documentation/io/built-in/google-bigquery/#exactly-once-semantics) mentions `WriteResult.getFailedInserts` does not work for Storage Write API. But now `WriteResult.getFailedStorageApiInserts` will return the failed rows for Storage Write API. 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

2023-09-25 22:24 UTC, RyuSA commented
assign to next reviewer

2023-09-25 22:35 UTC, RyuSA commented
/assign to next reviewer

2023-10-02 00:47 UTC, RyuSA commented
@kennknowles Could you take a look at this PR?

2023-10-02 01:35 UTC, liferoad commented
R: @ahmedabu98

2023-10-02 17:46 UTC, ahmedabu98 requested changes
Couple nits

Also I think we can remove the sentence `If there are data validation errors, the transform will throw a RuntimeException.` That doesn't happen anymore, data validation errors should also go to the failed inserts DLQ

2023-10-02 17:46 UTC, ahmedabu98 commented on website/www/site/content/en/documentation/io/built-in/google-bigquery.md
> +will contain the rows that failed to be written by the Storage Write API. If there are data validation errors, the
```suggestion
will contain the rows that failed to be written to the Storage Write API sink. If there are data validation errors, the
```

2023-10-05 07:12 UTC, RyuSA commented
@ahmedabu98 
Thank you. 👏 

> Also I think we can remove the sentence `If there are data validation errors, the transform will throw a RuntimeException.` That doesn't happen anymore, data validation errors should also go to the failed inserts DLQ

QQ I thought the "data validation errors" is this shema validation, isn't it? If no I'll quick fix the document.👍

https://github.com/apache/beam/blob/v2.50.0/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiLoads.java#L112

2023-10-05 14:34 UTC, ahmedabu98 commented
> QQ I thought the "data validation errors" is this schema validation, isn't it? 
I think data validation refers to schema validation, but I don't think that specific link is related. R rows with mismatched schema do go to the DLQ. In practice most failed rows in the DLQ are due to this. I'm not sure how the behavior was before, but we don't fail the transform/pipeline now.

I think the line in the link you sent checks that the coder for the `StorageApiWritePayload` object exists (this does not validate data schema).

2023-10-05 14:35 UTC, ahmedabu98 approved these changes
LGTM (should probably remove that sentence tho)

2023-10-09 05:13 UTC, RyuSA commented
@ahmedabu98 Sorry for the delay in getting back to you.

> (should probably remove that sentence

Yes, your comment resolved my QQ . The sentences should be removed. Thanks for letting me know.👍

I have added a new commit.👀.

2023-10-09 16:31 UTC, merged