Fix beam_LoadTests_Go_GBK_Dataflow_Batch job
apache/beam pull request #28960
Opened 2023-10-12 11:01 UTC by Amar3tto

### How has it been tested?
The job has been tested on Self-hosted GKE runners ubuntu 20.04.
The following test cases are passed:

- by adding a comment to the PR

![Screenshot from 2023-10-12 15-00-09](https://github.com/apache/beam/assets/17278361/83af22a9-3aaf-4950-be95-bc7c7cfdccdb)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

2023-10-13 08:08 UTC, aleksandr-dudko requested changes
Could you please, check the spaces and "#"  for all txt files: https://github.com/apache/beam/blob/fb455f6d7ee7fca6527923f2b10d42f21319c76d/.github/workflows/load-tests-job-configs/beam_LoadTests_Go_GBK_Dataflow_Batch_100b.txt#L16C31-L16C31
Thank you.

2023-10-16 14:42 UTC, andreydevyatkin reviewed
See the inline comments

2023-10-16 14:42 UTC, andreydevyatkin commented on .github/workflows/load-tests-job-configs/beam_LoadTests_Go_GBK_Dataflow_Batch_100b.txt
> -###############################################################################
Since we're updating `.txt` files as well, can we name it as `go_GBK_Dataflow_Batch_*.txt`?

2023-10-16 14:42 UTC, andreydevyatkin commented on .github/workflows/load-tests-job-configs/beam_LoadTests_Go_GBK_Dataflow_Batch_100b.txt
>  --project=apache-beam-testing
Can we remove `--project`, `--influx_db_name` and `--influx_hostname` since they are general options and are being applied at runtime?

2023-10-17 16:20 UTC, andreydevyatkin approved these changes
LGTM, thanks!

2023-10-17 19:39 UTC, merged