[YAML] Java Filter and explode operations.
apache/beam pull request #29110
Opened 2023-10-23 18:20 UTC by robertwb

This is a follow-up on top of https://github.com/apache/beam/pull/28657

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

2023-10-30 23:51 UTC, Polber requested changes

2023-10-30 23:51 UTC, Polber commented on sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/transforms/providers/JavaExplodeTransformProviderTest.java
> +import java.util.List;
I assume beam follows the no star import convention but I could be wrong

2023-10-30 23:51 UTC, Polber commented on sdks/python/apache_beam/yaml/standard_providers.yaml
Don't `Filter` and `Explode` need to be specified here?

2023-10-30 23:51 UTC, Polber commented on sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/providers/JavaExplodeTransformProvider.java
> +    return String.format("beam:schematransform:org.apache.beam:yaml:map_to_fields-java:v1");
Same URN as `MapToFields`

2023-10-30 23:51 UTC, Polber commented on sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/transforms/providers/JavaFilterTransformProvider.java
> +    return String.format("beam:schematransform:org.apache.beam:yaml:map_to_fields-java:v1");
Same URN as above

2023-10-31 00:16 UTC, robertwb commented on sdks/python/apache_beam/yaml/standard_providers.yaml
Fixed.

2023-10-31 17:28 UTC, Polber reviewed
LGTM. Should probably wait until #28657 is merged to make sure there are no conflicts

2023-11-01 00:38 UTC, Polber approved these changes

2023-11-01 14:30 UTC, merged