Duet AI Prompt - Beam YAML (no links)
apache/beam pull request #30440
Opened 2024-02-27 19:16 UTC by dariabezkorovaina

Adding a prompt about Beam YAML.
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

2024-02-29 14:14 UTC, olehborysevych requested changes
Left couple of comment

2024-02-29 14:14 UTC, olehborysevych commented on learning/prompts/documentation-lookup-nolinks/50_beam_yaml.md
> +Prompt: Can I create Apache Beam pipelines using YAML?
add line break

2024-02-29 14:14 UTC, olehborysevych commented on learning/prompts/documentation-lookup-nolinks/50_beam_yaml.md
> +Response: The Beam YAML API enables the creation of basic Apache Beam pipelines using YAML syntax, which can be edited with any text editor. This intuitive, declarative syntax simplifies pipeline aut
add line break

2024-02-29 14:14 UTC, olehborysevych commented on learning/prompts/documentation-lookup-nolinks/50_beam_yaml.md
> +Response: The Beam YAML API enables the creation of basic Apache Beam pipelines using YAML syntax, which can be edited with any text editor. This intuitive, declarative syntax simplifies pipeline aut
i suggest to replace word syntax with file, because it's not that syntax can be edited but a file or a document

2024-02-29 14:14 UTC, olehborysevych commented on learning/prompts/documentation-lookup-nolinks/50_beam_yaml.md
> +You can execute a pipeline defined in a YAML file using the standard `python -m` command.
please add how you specify a yaml file for execution

2024-02-29 14:40 UTC, dariabezkorovaina commented
@olehborysevych fixed - please take a look :)

2024-03-05 14:10 UTC, dariabezkorovaina commented
Hi @damccorm :) Please review one new prompt about Beam YAML when you have a chance.

2024-03-05 14:22 UTC, dariabezkorovaina commented on learning/prompts/documentation-lookup-nolinks/50_beam_yaml.md
> +python -m apache_beam.yaml.main --yaml_pipeline_file=/path/to/pipeline.yaml [other pipeline options such as the runner]
@damccorm, we used the [official Apache Beam documentation about Beam YAML](https://beam.apache.org/documentation/sdks/yaml/) for examples, and we noticed that there is a command that looks outdated:
--yaml_pipeline_file=

In the [example pipelines](https://gist.github.com/robertwb/2cb26973f1b1203e8f5f8f88c5764da0), the correct command is: 
--pipeline_spec_file=

Should we use the new command in the prompt?

We also created a GitHub issue to report this inconsistency in the documentation.

2024-03-05 17:48 UTC, damccorm approved these changes
Thanks

2024-03-05 17:48 UTC, merged

2024-03-06 09:53 UTC, dariabezkorovaina commented on learning/prompts/documentation-lookup-nolinks/50_beam_yaml.md
> +python -m apache_beam.yaml.main --yaml_pipeline_file=/path/to/pipeline.yaml [other pipeline options such as the runner]
Thank you, Danny! Noted:)