Fix TextIO not fully reading a GCS file when decompressive transcoding happens
apache/beam pull request #33384
Opened 2024-12-15 05:07 UTC by shunping

For GCS, we determine the splittability based on whether a file meets decompressive transcoding criteria.

When decompressive transcoding occurs, the size returned from metadata (i.e. the gzipped file size) does not match the size of the content returned (i.e. original data size). In this case, we force the source to be unsplittable to ensure all its content is read.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

2024-12-18 19:02 UTC, kennknowles requested changes

2024-12-18 19:02 UTC, kennknowles commented on sdks/python/apache_beam/io/filesystem.py
> +    return True
This should probably not always be true. If this is a default, perhaps it should not have a default but be abstract and we implement for various filesystems. If it is the default, comment so we understand that is why it ignores the argument.

2024-12-18 19:02 UTC, kennknowles commented on sdks/python/apache_beam/io/gcp/gcsfilesystem.py
> +      if file_metadata.get('content_encoding', None) == 'gzip':
Doesn't the content-type also have to be a particular thing in addition to the content-encoding being set to gzip?

2024-12-18 19:12 UTC, shunping commented on sdks/python/apache_beam/io/filebasedsource.py
> +  return True
Right, I will have to clean this up when I move the draft to review ready ;)

2025-01-04 03:10 UTC, shunping commented on sdks/python/apache_beam/io/gcp/gcsfilesystem.py
> +      if file_metadata.get('content_encoding', None) == 'gzip':
The line has been removed in the new change.

2025-01-04 03:11 UTC, shunping commented on sdks/python/apache_beam/io/filesystem.py
> +    return True
The line has been removed in the new change.

2025-01-04 03:11 UTC, shunping commented on sdks/python/apache_beam/io/filebasedsource.py
> +  return True
The line has been removed in the new change.

2025-01-08 19:25 UTC, kennknowles commented on sdks/python/apache_beam/io/gcp/gcsio.py
> +        blob, chunk_size=chunk_size, retry=retry, raw_download=raw_download)
Will these be a stable API? It is not documented at https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.fileio.BlobReader

2025-01-08 19:27 UTC, kennknowles approved these changes
The change is so simple now. Nice! If the GCS client library breaks us later, then we can issue an update, but I just wanted to ask if it was going to be stable.

2025-01-08 19:41 UTC, shunping commented on sdks/python/apache_beam/io/gcp/gcsio.py
> +        blob, chunk_size=chunk_size, retry=retry, raw_download=raw_download)
Good question and that is a valid concern. 

The `raw_download` is included as one of the valid download parameters within the kwargs:
- https://github.com/googleapis/python-storage/blob/ca998db2db7c7b028f6fc145f1cc6b8b2c2a967b/google/cloud/storage/fileio.py#L108
- https://github.com/googleapis/python-storage/blob/ca998db2db7c7b028f6fc145f1cc6b8b2c2a967b/google/cloud/storage/fileio.py#L38

Let me ask the devs of the GCS lib about what is their plan for that API.

2025-01-08 23:38 UTC, shunping commented on sdks/python/apache_beam/io/gcp/gcsio.py
> +        blob, chunk_size=chunk_size, retry=retry, raw_download=raw_download)
Just confirmed it is a stable API, and the devs of the library will update their doc to address that.

2025-01-09 17:56 UTC, shunping commented
Add a cross-link to https://github.com/googleapis/python-storage/issues/1406, as we will need to clean up the workaround after the previous issue is fixed.

2025-01-09 18:53 UTC, damccorm approved these changes
Thanks!

2025-01-09 18:54 UTC, merged