[Prism] Use the worker-id gRPC metadata
apache/beam pull request #33438
Opened 2024-12-23 02:57 UTC by damondouglas

This PR closes #32167 via implementation of a worker.MultiplexW to forward FnAPI gRPC requests to *W stored by id that matches the worker-id gRPC context metadata. In addition to typical go test workflow, to validate this PR `./gradlew :runners:portability:java:ulrLoopbackValidatesRunnerTests -PjobEndpoint=localhost:8073` was ran on a few initial tests. The `idle_shutdown_timeout` was tested by visual inspection to validate the additional service does not block the executable from shutting down.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[![Build python source distribution and wheels](https://github.com/apache/beam/workflows/Build%20python%20source%20distribution%20and%20wheels/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[![Python tests](https://github.com/apache/beam/workflows/Python%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[![Java tests](https://github.com/apache/beam/workflows/Java%20Tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[![Go tests](https://github.com/apache/beam/workflows/Go%20tests/badge.svg?branch=master&event=schedule)](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

2024-12-24 00:26 UTC, damondouglas commented
Python sends an empty string for worker_id key in the gRPC metadata. Debugging the `workerFromMetadataCtx` method, I see a worker_id sent over when running `python apache_beam/examples/wordcount.py`, except for a single instance.

The error `worker I'd in ctx metadata is an empty string` is specific to `id == ""`. This is a conditional after `grpcx.ReadWorkerID` successfully passes all checks for available `metadata.FromIncomingContext`, and the `metadata.MD` has the `worker_id` key, and finally that the length of the `metadata.MD[worker_id]` is 1.

<summary>

`worker id in ctx metadata is an empty string`

<details>
```
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "worker id in ctx metadata is an empty string"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"worker id in ctx metadata is an empty string", grpc_status:2, created_time:"2024-12-23T16:08:00.205761402-08:00"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py", line 311, in _execute
    response = task()
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py", line 386, in <lambda>
    lambda: self.create_worker().do_instruction(request), request)
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py", line 657, in do_instruction
    return getattr(self, request_type)(
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py", line 694, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "sdks/python/apache_beam/runners/worker/bundle_processor.py", line 1274, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "sdks/python/apache_beam/runners/worker/bundle_processor.py", line 237, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 567, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 569, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 260, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 263, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 1159, in apache_beam.runners.worker.operations.CombineOperation.process
  File "apache_beam/runners/worker/operations.py", line 1163, in apache_beam.runners.worker.operations.CombineOperation.process
  File "apache_beam/runners/worker/operations.py", line 569, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 260, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 263, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 1159, in apache_beam.runners.worker.operations.CombineOperation.process
  File "apache_beam/runners/worker/operations.py", line 1163, in apache_beam.runners.worker.operations.CombineOperation.process
  File "apache_beam/runners/worker/operations.py", line 569, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 260, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 263, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 950, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 951, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1503, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1591, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1501, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 689, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1686, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1799, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 263, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 950, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 951, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1503, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1591, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1501, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 917, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1059, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1686, in apache_beam.runners.common._OutputHandler.handle_process_outputs
  File "apache_beam/runners/common.py", line 1799, in apache_beam.runners.common._OutputHandler._write_value_to_tag
  File "apache_beam/runners/worker/operations.py", line 263, in apache_beam.runners.worker.operations.SingletonElementConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 950, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 951, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 1503, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 1612, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 1501, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 917, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 1000, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "sdks/python/apache_beam/runners/worker/bundle_processor.py", line 499, in __getitem__
    self._cache[target_window] = self._side_input_data.view_fn(raw_view)
  File "sdks/python/apache_beam/pvalue.py", line 389, in <lambda>
    lambda iterable: from_runtime_iterable(iterable, view_options))
  File "sdks/python/apache_beam/pvalue.py", line 509, in _from_runtime_iterable
    head = list(itertools.islice(it, 2))
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py", line 1289, in _lazy_iterator
    input_stream, continuation_token = self._get_raw(
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py", line 1307, in _get_raw
    self._underlying.get_raw(state_key, continuation_token))
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py", line 1094, in get_raw
    response = self._blocking_request(
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py", line 1134, in _blocking_request
    raise self._exception
  File ".pyenv/versions/3.10.15/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File ".pyenv/versions/3.10.15/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "sdks/python/apache_beam/runners/worker/sdk_worker.py",  [...]

2024-12-30 21:16 UTC, damondouglas commented
R: @lostluck

2024-12-30 23:04 UTC, lostluck requested changes
Close but we can improve it! This top comment is a summary of what the more pointed comments are mentioning.

As it stands, we should not introduce a package global (the worker pool). That will only make things harder for later maintainers, so getting the plumbing right now is a good idea. 

The main adjustment would be to not make it so we need to add 4 new locations for creating the net.Listen calls. We shouldn't need to be adding *more* of those as a result of this work. In principle, we should be getting fewer of them.

First, make the worker pool a struct. You already have this type in the form of the MultiplexW type. Move the map, and the lock onto that, and out of the package namespace.

Then we add a method to register onto a provided GRPC server, and stop making it's own. This lets us re-use an existing GRPC server, such as the one for JobManagement.

prism.CreateJobServer can be updated to create the pool and pass it to jobservices.NewServer. For it's part, the jobservices package can have an interface for accepting this worker factory, without even refering directly to any of the types from the `worker` package. This lets the Job spit out prefixed workers.

The main gap is that worker production method would need to be part of the interface, so it can be exposed via the Job type. That method can return an any, that we can then cast to a *worker.W to do the remaining worker set up. I don't love this, but it's not the end of the world. If that type is wrong, everything breaks very early, which is good.

2025-01-02 17:55 UTC, lostluck approved these changes
Some largely minor comments I trust you can change without an additional review gate. Please make them before merging.

Please let me know if you have questions or want a subsequent final review.

2025-01-02 17:55 UTC, lostluck commented on sdks/go/pkg/beam/runners/prism/internal/execute.go
> -	})
We may still want this block of code moved to the MakeWorker method. This checks that the SDK has connected to the worker and serves as a liveness check for the SDK.

If we don't get this connection, the job *must* not hang forever. It's better that prism fails the job than waits forever, since it indicates there's something weird/bad going on in the SDK side.

2025-01-02 17:55 UTC, lostluck commented on sdks/go/pkg/beam/runners/prism/internal/worker/worker.go
> +	mw                 *MultiplexW
Please move `mw` to the higher block, possibly right under the Unimplemented interface embeddings. Consider renaming it `parentPool`, which is how it's related to this W.

Brevity in field and variable names is up to convention and context. In this case, a slightly longer name is better since it's only used in two places. See https://go.dev/talks/2014/readability.slide#24 for further guidance.

Positioned where it is, it's implied that accessing `mw` is protected by the mutex `mu`. This pattern is known as a `Mutex Hat`. See https://go.dev/talks/2014/readability.slide#21.

2025-01-02 17:55 UTC, lostluck commented on sdks/go/pkg/beam/runners/prism/internal/worker/worker.go
> +	mw := &MultiplexW{
Note that in *this* context, `mw` is a good name, it's used many times in a short context, meaning a shorter name is more readable. The scope is just barely a dozen lines long.

2025-01-02 17:55 UTC, lostluck commented on sdks/go/pkg/beam/runners/prism/internal/worker/worker.go
> +type MultiplexW struct {
Please add a comment about the purpose of MultiplexW.

If only because we'll get a lint comment about it on importing the code.

2025-01-02 17:55 UTC, lostluck commented on sdks/go/pkg/beam/runners/prism/internal/worker/worker.go
> +func New(lis net.Listener, g *grpc.Server, logger *slog.Logger) *MultiplexW {
Naming is one of the hardest problems in computer science.

Here's the current rundown:

Since the package is named `worker` naming the type `Worker` leads to stuttering when using the type elsewhere, which is visually unappealing. Hence why we named the original abstraction type `W`.

Since external workers would be calling the function qualified with the package name, we used a shorter name for it, so callers would simply be `worker.New`, instead of `worker.NewWorker`. (This avoids the stuttering.)

But now this function is not creating a direct worker analog, but something else. So instead I'd recommend a new name: `NewMultiplexer`. This tells users that they aren't getting a worker directly, but instead a more complex object.

2025-01-02 17:55 UTC, lostluck commented on sdks/python/test-suites/portable/common.gradle
> +    options += " --environment_type=${workerType}"
Is this change because something weird was going on when environment type was "docker"?

2025-01-02 17:55 UTC, lostluck commented on sdks/go/pkg/beam/runners/prism/internal/worker/worker_test.go
> -	w.lis = lis
I will note that we used bufconn here to avoid actually using a network port during the unit tests. Not a hard blocker, but it would be nice to try to maintain that instead of using a new port every time.

What lead you to stop using the buffered connection?

2025-01-02 20:48 UTC, damondouglas commented on sdks/go/pkg/beam/runners/prism/internal/worker/worker_test.go
> -	w.lis = lis
I was able to add it back. I saw a deprecated warning about the use of DialContext but I see you had it before causing no issues so I added it back.

2025-01-02 20:50 UTC, damondouglas commented on sdks/go/pkg/beam/runners/prism/internal/execute.go
> -	})
I added this back. Thank you.

2025-01-02 21:44 UTC, lostluck commented on sdks/go/pkg/beam/runners/prism/internal/worker/worker_test.go
> +	//lis, err := net.Listen("tcp", ":0")
Sweet. Just need to clean up the commented out bits then.

2025-01-03 01:31 UTC, damondouglas commented on sdks/python/test-suites/portable/common.gradle
> +    options += " --environment_type=${workerType}"
I think this was an artifact of trying to run as a separate gRPC service.

2025-01-03 18:11 UTC, merged